### ISSUE TITLE
Error handler renders API responses even for non-api requests responding with a 404

### ISSUE THREAD

**Issue by benbieler** [Sententiaregum/Sententiaregum#233]
### Description

Currently when going to:

```
http://sententiaregum.dev/foo
```

the server side routing will take over.
On the other hand:

```
http://sententiaregum.dev/#/foo
```

will show you the custom ReactJS 404 page.

<del>Ontop hashbang Url's are very bad for SEO...</del>

**Comment by Ma27** [comment]
### First idea of a approach to solve the issue

at first, I should note that actually the app is separated into two parts:

1.: REST API (all URLs prefixed with _/api_)
2.: Frontend Application (all the other URLs)

In order to solve inconsistencies between the Backend 404 handler and the frontend 404 handler I think that a suitable solution would be a custom symfony2 error handler which detects whether the API is called or a broken frontend request has been submitted. In the last case the handler should redirect to a react 404 page.

### Removal of hashbangs?

At first I think that hashbangs help to improve the UX and give a feeling of a "real desktop applications" as everything will be rendered by ReactJS without sending a HTTP request, so the rendering process is now very fast.
The second thing is that google is able to analyze dynamically rendered content quite well: https://googlewebmastercentral.blogspot.de/2014/05/understanding-web-pages-better.html

Furthermore I doubt that a social network where content of certain users is simply visible to other users and noone else is SEO that important. The landing page has a quite simple structure and should be easy to be analyzed by google bot. This page (and the registration page maybe) should be the only ones that really need to be analyzed. The rest are visible for registered people only and therefore it is IMHO not necessary to index them.

**Comment by Ma27** [comment]
added backend label as the symfony api is also affected by that issue.

**Comment by benbieler** [comment]
Seams fine to me👍

**Comment by benbieler** [comment]
I'm no Symfony pro, but in NodeJs you would solve this problem by doing  something realy simple like this: 

``` js
app.get('/*', function(req, res){
    res.render('index')
});
```

in index.html the frontend routing will take over.

**Comment by Ma27** [comment]
ok, relabeling this and assigning to a milestone

**Comment by Ma27** [comment]
@benbieler I'm aware of such an approach since many javascript based routers do it like this (also frontend routers such as `react-router`).

The approach I prefer is an exception handler which listens on 404 exceptions and will be triggered with a high priority in order to call it before all the other exception handlers and this one would check whether we're inside the API or not and would build a generic response for it.

**Comment by Ma27** [comment]
changed title to express the actual issue even better.

**Comment by benbieler** [comment]
:+1:
