### ISSUE TITLE
Use reCAPTCHA

### ISSUE THREAD

**Issue by benbieler** [Sententiaregum/Sententiaregum#333]
Using reCAPTCHA(https://www.google.com/recaptcha/intro/index.html) will make it harder for bots.

**Comment by Ma27** [comment]
this one might help: https://github.com/appleboy/react-recaptcha

Have to think about whether or not it makes sense to include it, so let's discuss about it in the next days. When we found an appropriate solution, I'll assign it to a milestone, so you can start working on it :)

**Comment by Ma27** [comment]
@benbieler I think that using reCaptcha might be worth a try as it seems to include some sort of an audio captcha which helps when failing on the image.
But please keep in mind that a cheap JS-side check won't fix all problems: the bigger issue is our API. When introducing a captcha we need some kind of a middleware or enhance our registration service in order to validate the captcha properly. If we find a suitable solution for this, it might be a nice addition to our protection services like the authentication attempt checker and the user activation (which makes the job for bots harder, too).

**Comment by Ma27** [comment]
@benbieler is there anything you'd like to add? Unless, I'll make this ready to work on, so you can start implementing this when you've got enough time :)

**Comment by benbieler** [comment]
@Ma27 No, seems all fine to me. I would start with this on the weekend

**Comment by Ma27** [comment]
@benbieler as already mentioned, we need to generate the whole stuff in our backend and expose it somehow to the frontend. I'd use this PHP package (https://github.com/google/recaptcha) in the backend as I'd like to avoid having a captcha in the frontend, but no protection for the API (which would made the whole work useless)

**Comment by Ma27** [comment]
ready to be merged now
